### ISSUE TITLE
Language shouldn’t immediately get chosen

### ISSUE THREAD

**Issue by chucker** [ricardoboss/Prolangle#117] opened 2024-01-27 10:05 UTC
### Is your feature request related to a problem? Please describe.

Choosing from the autocomplete currently immediately counts as a guess.

### Describe the solution you'd like

We should have a separate button instead.

### Additional context

This would also be consistent with Progle and Metazooa.

**Comment by ricardoboss** [comment] 2024-01-28 15:14
Dupe of https://github.com/ricardoboss/Prolangle/issues/76

**Closed by ricardoboss** 2024-01-28 15:14 UTC
Labels: enhancement
